#!/usr/bin/env bash

OPT_VERBOSE=0

MAJOR_VERSION="3"

# exporting because colours are maybe used in subshells
# not 100% sure, would be good to check
export term_reset=
export term_bold=
export term_fg_blue=
export term_fg_green=
export term_fg_red=
export term_fg_white=
export term_fg_yellow=

find_me() {
    # Find where we are installed through possible system links
    local SOURCE="${BASH_SOURCE[0]}"
    # resolve $SOURCE until the file is no longer a symlink
    while [ -h "${SOURCE}" ]; do
        PATH_BASE="$(cd -P "$(dirname "${SOURCE}")" && pwd)"
        SOURCE="$(readlink "${SOURCE}")"
        # if SOURCE was a relative symlink, we need to resolve it
        # relative to the path where the symlink file was located
        [[ ${SOURCE} != /* ]] && SOURCE="${PATH_BASE}/${SOURCE}"
    done
    PATH_BASE="$(cd -P "$(dirname "${SOURCE}")/.." && pwd)"
}
find_me

# Try to only use in subshells
cdd() {
    cd "${1}" || {
        error "Unable to cd to ${1}"
        exit 1
    }
}

################
## start menu ##
################

usage() {
    main_title
    local GROUP_LIST_DISPLAY
    GROUP_LIST_DISPLAY="$(implode "|" "${DOTFILE_GROUP_LIST[@]}" | sed 's/|shared//')"
    cat << EOF
${term_fg_yellow}Usage:${term_reset}
  dotfile [options] <command> <args>

${term_fg_yellow}Options:${term_reset}
  ${term_fg_green}-h, --help${term_reset}         Display general usage or command help
  ${term_fg_green}--version${term_reset}          Display version
  ${term_fg_green}-p, --preview${term_reset}      Preview changes without writing
  ${term_fg_green}-g, --group${term_reset}        Use platform group instead of "shared" ie. (${GROUP_LIST_DISPLAY})
  ${term_fg_green}-v, --verbose${term_reset}      Set verbosity level

${term_fg_yellow}Commands:${term_reset}
  ${term_fg_green}sync${term_reset}               Sync config dotfiles to home dir
  ${term_fg_green}import${term_reset} <file...>   Move file to config and create a link
  ${term_fg_green}export${term_reset} <file...>   Remove link and move file back from config
  ${term_fg_green}config${term_reset}             Edit config file

EOF
}

# Empty call
dotfile_() {
    usage
}

# Bad call
dotfile_call_() {
    usage
    return 1
}

dotfile_option_v() {
    dotfile_option_verbose "${@}"
}
dotfile_option_verbose() {
    OPT_VERBOSE=1
    dispatch dotfile "$@"
}

dotfile_option_version() {
    echo "Version ${term_fg_yellow}${MAJOR_VERSION}${term_reset}"
}

dotfile_option_h() {
    dotfile_option_help "${@}"
}
dotfile_option_help() {
    export HELP=1
    dispatch dotfile "${@}"
}

dotfile_option_p() {
    dotfile_option_preview "${@}"
}
dotfile_option_preview() {
    export PREVIEW=1
    dispatch dotfile "$@"
}

dotfile_option_g() {
    dotfile_option_group "${@}"
}
dotfile_option_group() {
    export ACTIVE_GROUP="${1}"
    local GROUP
    local FOUND=0
    for GROUP in "${DOTFILE_GROUP_LIST[@]}"; do
        if [ "${ACTIVE_GROUP}" = "${GROUP}" ]; then
            FOUND=1
        fi
    done
    if [ "${FOUND}" -eq 0 ]; then
        error "Invalid group: ${ACTIVE_GROUP}"
        return 1
    fi
    shift

    dispatch dotfile "${@}"
}

dotfile_command_config() {
    local CONFIG_FILE="${TRUE_HOME_DIR}/.config/dotfile/config.ini"

    if [ ! -f "${CONFIG_FILE}" ]; then
        echo "Missing config file: ${CONFIG_FILE}"
        reutrn 1
    fi

    ${EDITOR:-vi} "${CONFIG_FILE}"
}

dotfile_command_export() {
    title_export

    if [ -z "${*}" ]; then
        echo "Missing files to export"
        echo
        return 1
    fi

    if [ "${PREVIEW}" -eq 1 ]; then
        info "Preview"
        echo
    fi

    heading "Export ${term_fg_blue}$(implode " " "${@}")${term_reset}"

    local FILES=("${@}")
    local FILE
    local STATUS=0
    for FILE in "${FILES[@]}"; do
        export_dotfile "${FILE}" || STATUS=1
    done
    return "${STATUS}"
}

dotfile_command_import() {
    if [ -z "${*}" ]; then
        echo "Missing files to import"
        echo
        return 1
    fi

    title_import

    if [ "${PREVIEW}" -eq 1 ]; then
        info "Preview"
        echo
    fi

    heading "Import ${term_fg_blue}$(implode " " "${@}")${term_reset} into ${term_fg_blue}${DOTFILES_DIR}/${ACTIVE_GROUP}${term_reset}"

    local FILES=("${@}")
    local FILE
    local STATUS=0
    for FILE in "${FILES[@]}"; do
        import_dotfile "${ACTIVE_GROUP}" "${FILE}" || STATUS=1
    done
    return "${STATUS}"
}

dotfile_command_sync() {
    title_sync
    display_ensure_filesystem || return 1
    sync_config_to_home || return 1
}

dotfile_command_test() {
    :
}

##############
## end menu ##
##############

load_global_variables() {
    HELP="${HELP-0}"
    PREVIEW="${PREVIEW-0}"
    ACTIVE_GROUP=shared

    term_reset=$(tput sgr0)
    term_bold=$(tput bold)
    term_fg_blue=$(tput setaf 4)
    term_fg_green=$(tput setaf 2)
    term_fg_red=$(tput setaf 1)
    term_fg_white=$(tput setaf 7)
    term_fg_yellow=$(tput setaf 3)

    # Platform
    local UNAME
    UNAME="$(uname -a)"
    local LINUX=0
    local LINUX_LAPTOP=0
    local OSX=0
    MSYS=0
    local WSL=0
    local WINDOWS=0
    if [[ ${UNAME} =~ ^Linux.*$ ]]; then
        LINUX=1
        # laptop-ish types:
        # - 8 portable
        # - 9 laptop
        # - 10 notebook
        # - 11 handheld
        # - 14 sub notebook
        # - 30 tablet
        if [ -f /sys/class/dmi/id/chassis_type ] && [[ $(cat /sys/class/dmi/id/chassis_type) =~ (8|9|10|11|14|30) ]]; then
            LINUX_LAPTOP=1
        fi
    fi
    if [[ ${UNAME} =~ ^Darwin.*$ ]]; then
        OSX=1
    fi
    if [[ ${UNAME} =~ ^(MINGW|MSYS).*$ ]]; then
        MSYS=1
        WINDOWS=1
    fi
    if [[ ${UNAME} =~ ^.*[Mm]icrosoft.*$ ]]; then
        WSL=1
        WINDOWS=1
    fi

    # Home dir
    HOME_DIR=~
    TRUE_HOME_DIR="${TRUE_HOME_DIR-${HOME_DIR}}"
    [ "${LINUX}" -eq 1 ] && [ "${EUID}" -eq 0 ] && IS_ROOT=1 || IS_ROOT=0

    # Depends on loaded config
    config_dir=
    custom_groups=
    ensure_config || return 1
    if [ ! -d "${config_dir}" ]; then
        error "failed to load a valid config dir"
        return 1
    fi

    DOTFILE_MARKER=".dotfilemarker"
    DOTFILES_DIR="${config_dir/${HOME_DIR}\//${TRUE_HOME_DIR}/}"
    SYNC_EXCLUDE_LIST=(".git" ".gitignore" ".DS_Store" "${DOTFILE_MARKER}")
    [ "${IS_ROOT}" -eq 0 ] \
        && BACKUP_DIR="${TRUE_HOME_DIR}/.config/dotfile/backup" \
        || BACKUP_DIR="${TRUE_HOME_DIR}/.config/dotfile/backup_root"
    DOTFILES_REPO="${config_repo}"
    DOTFILE_GROUP_LIST=()

    # Order of dotfile groups, higher overrides lower
    if [ -n "${custom_groups}" ]; then
        IFS="," read -ra SPLIT_CUSTOM_GROUPS <<< "${custom_groups}"
        for CUSTOM_GROUP in "${SPLIT_CUSTOM_GROUPS[@]}"; do
            DOTFILE_GROUP_LIST+=("${CUSTOM_GROUP}")
        done
    fi
    [ "${MSYS}" -eq 1 ] && DOTFILE_GROUP_LIST+=("msys")
    [ "${WSL}" -eq 1 ] && DOTFILE_GROUP_LIST+=("wsl")
    [ "${WINDOWS}" -eq 1 ] && DOTFILE_GROUP_LIST+=("windows")
    [ "${OSX}" -eq 1 ] && DOTFILE_GROUP_LIST+=("darwin")
    [ "${IS_ROOT}" -eq 1 ] &&  DOTFILE_GROUP_LIST+=("root")
    [ "${LINUX_LAPTOP}" -eq 1 ] && DOTFILE_GROUP_LIST+=("linux_laptop")
    [ "${LINUX}" -eq 1 ] && DOTFILE_GROUP_LIST+=("linux")
    DOTFILE_GROUP_LIST+=("shared")

    local DOTFILE_GROUP
    for DOTFILE_GROUP in "${DOTFILE_GROUP_LIST[@]}"; do
        ensure_dir "${DOTFILES_DIR}/${DOTFILE_GROUP}" || return 1
        ensure_file "${DOTFILES_DIR}/${DOTFILE_GROUP}/${DOTFILE_MARKER}" || return 1
    done
}

LIB_INCLUDES=(
    "bashful/bashful.sh"
    "workshop/dispatch.sh"
    "bash-ini-parser/bash-ini-parser.sh"
)
for LIB_INCLUDE in "${LIB_INCLUDES[@]}"; do
    # unfortunately has to be dynamic because the base path isn't known
    # the libs have to be resolved relative to the installed script
    # "/usr/local/bin/dotfile" or the one in this repo
    # shellcheck disable=SC1090
    source "${PATH_BASE}/lib/${LIB_INCLUDE}"
done

main_title() {
    doc_title << 'EOF'
         __      __  _____ __
    ____/ /___  / /_/ __(_) /__
   / __  / __ \/ __/ /_/ / / _ \
  / /_/ / /_/ / /_/ __/ / /  __/
  \__,_/\____/\__/_/ /_/_/\___/

EOF
}

title_export() {
    doc_title << 'EOF'
                                __
    ___  _  ______  ____  _____/ /_
   / _ \| |/_/ __ \/ __ \/ ___/ __/
  /  __/>  </ /_/ / /_/ / /  / /_
  \___/_/|_/ .___/\____/_/   \__/
          /_/

EOF
}

title_import() {
    doc_title << 'EOF'
      _                            __
     (_)___ ___  ____  ____  _____/ /_
    / / __ `__ \/ __ \/ __ \/ ___/ __/
   / / / / / / / /_/ / /_/ / /  / /_
  /_/_/ /_/ /_/ .___/\____/_/   \__/
             /_/

EOF
}

title_sync() {
    doc_title << 'EOF'
     _______  ______  _____
    / ___/ / / / __ \/ ___/
   (__  ) /_/ / / / / /__
  /____/\__, /_/ /_/\___/
       /____/

EOF
}

debug() {
    if [ "${OPT_VERBOSE}" -eq 0 ]; then
        return
    fi
    echo "DEBUG: ${1}"
}

info() {
    # TODO
    # term_bold
    # term_fg_blue
    # term_fg_white
    # term_reset

    # Shorten home paths, if they exist.
    msg=${1//$HOME/\~}

    echo -e "${term_bold}${term_fg_blue}==> ${term_fg_white}${msg}${term_reset}" >&2
}

error() {
    # TODO
    # term_bold
    # term_fg_red
    # term_fg_white
    # term_reset

    # Shorten home paths, if they exist.
    msg=${1//$HOME/\~}

    echo -e "${term_bold}${term_fg_red}ERROR: ${term_fg_white}${msg}${term_reset}" >&2
}

extname() {
    # filename has no extension
    [[ "${1}" == *.* ]] || return 0

    echo ".${1##*.}"
}

filename() {
    basename "$1" "$(extname "$1")"
}

# Execute git command in dotfiles dir
dotfile_git() {
    # cd in a subshell to avoid altering current shell state
    (
      cdd "${DOTFILES_DIR}"
      git "${@}"
    )
}

dotfile_git_add() {
    local TO_ADD="${1}"
    local IGNORE_RULES
    if ! dotfile_git add "${TO_ADD}"; then
        error "Failed to stage ${TO_ADD} in git"

        # Check if failed because of ignore rules
        IGNORE_RULES="$(dotfile_git check-ignore -v "${TO_ADD}")"
        if [ -n "${IGNORE_RULES}" ]; then
            echo
            info "File ignored by git"
            echo "${IGNORE_RULES}"
        fi

        return 1
    fi

    return 0
}

clone_repo() {
    local GIT_REPO="${1}"
    local NAME="${2}"

    if ! git clone "${GIT_REPO}" "${NAME}"; then
        error "Failed to clone ${GIT_REPO}"
        return 1
    fi

    info "Cloned ${GIT_REPO} => ${NAME}"
    return 0
}

display_ensure_dir() {
    local DIR="${1}"
    local NAME="${2}"
    local MESSAGE="${NAME} ${DIR}"

    if [ -z "${DIR}" ]; then
        error "Dir param not set"
        return 1
    fi

    if [ -z "${NAME}" ]; then
        error "Name param not set"
        return 1
    fi

    if [ -d "${DIR}" ]; then
        info "Found ${MESSAGE}"
        return 0
    fi

    ensure_dir "${DIR}"
    local SUCCESS="${?}"

    if [ "${SUCCESS}" -eq 0 ]; then
        info "Created ${MESSAGE}"
    fi

    return "${SUCCESS}"
}

ensure_dir() {
    local DIR="${1}"

    if [ -z "${DIR}" ]; then
        error "Dir param not set"
        return 1
    fi

    if [ -d "${DIR}" ]; then
        return 0
    fi

    if ! mkdir -p "${DIR}"; then
        error "Failed to create ${DIR}"
        return 1
    fi

    return 0
}

ensure_file() {
    local FILE="${1}"

    [ -f "${FILE}" ] && return 0

    if ! touch "${FILE}"; then
        error "Failed to create ${FILE}"
        return 1
    fi

    return 0
}

# Create a link in a "smart" way
#
# - check for existing link
# - remove broken links
# - move existing file to backup dir
# - use `mklink` or `ln -s` depending on platform
# - support "preview" mode
#
smart_link() {
    local GROUP="${1%/}"
    local FILE_REF="${2}"
    local FILE_NAME="${2##*/}"

    local SRC_FILE="${DOTFILES_DIR}/${GROUP}/${FILE_REF}"
    local DEST_FILE="${HOME_DIR}/${FILE_REF}"
    local DEST_DIR="${DEST_FILE%/*}"
    local DISPLAY_FILE_REF="${FILE_REF}"

    if [ -n "${GROUP/shared/}" ]; then
        DISPLAY_FILE_REF+=" (${GROUP})"
    fi

    # Link exists but doesn't point to the right file
    if [ -L "${DEST_FILE}" ]; then
        local LINK_ISSUE=()
        local LINKED_TO
        LINKED_TO="$(readlink "${DEST_FILE}")"
        if [ "${SRC_FILE}" != "${LINKED_TO}" ]; then
            LINK_ISSUE=(" Incorrect" "${DISPLAY_FILE_REF} (${LINKED_TO} should be ${SRC_FILE})")
        elif  [ ! -e "${DEST_FILE}" ]; then
            LINK_ISSUE=("    Broken" "${DISPLAY_FILE_REF}")
        fi

        if [ "${#LINK_ISSUE[@]}" -gt 0 ]; then
            if [ "${PREVIEW}" -eq 1 ]; then
                echo_status "${term_fg_red}" "${LINK_ISSUE[@]}"
                return 1
            fi

            # Remove bad link
            echo_status "${term_fg_green}" "    Fixing" "${DISPLAY_FILE_REF}"
            rm "${DEST_FILE}"
        fi
    fi

    # Already linked
    if [ -L "${DEST_FILE}" ]; then
        echo_status "${term_fg_green}" "    Linked" "${DISPLAY_FILE_REF}"
        return 0
    fi

    # File already exists
    if [ -e "${DEST_FILE}" ]; then
        if [ -f "${SRC_FILE}" ] && [ -f "${DEST_FILE}" ] \
                && cmp --silent "${SRC_FILE}" "${DEST_FILE}"; then
            # Delete if files are identical
            if [ "${PREVIEW}" -eq 1 ]; then
                echo_status "${term_fg_red}" "    Remove" "${DISPLAY_FILE_REF} (identical contents)"
            else
                echo_status "${term_fg_yellow}" "   Removed" "${DISPLAY_FILE_REF} (identical contents)"
                rm "${DEST_FILE}"
            fi
        else
            if [ "${PREVIEW}" -eq 1 ]; then
                echo_status "${term_fg_yellow}" "    Backup" "${DISPLAY_FILE_REF}"

                # File contents differ
                if [ -f "${SRC_FILE}" ] && [ -f "${DEST_FILE}" ] \
                        && ! cmp --silent "${SRC_FILE}" "${DEST_FILE}" && [ "${OPT_VERBOSE}" -eq 1 ]; then
                    git --no-pager diff --no-index "${SRC_FILE}" "${DEST_FILE}" || {
                        error "failed to display diff in pager"
                        return 1
                    }
                fi
            else
                backup_move "${DEST_DIR}" "${FILE_NAME}" "${DISPLAY_FILE_REF}" || return 1
            fi
        fi
    fi

    # Preview
    if [ "${PREVIEW}" -eq 1 ]; then
        local COLOUR="${term_fg_white}"
        if [ ! -d "${DEST_DIR}" ]; then
            COLOUR="${term_fg_yellow}"
        fi
        echo_status "${COLOUR}" "      Link" "${DISPLAY_FILE_REF}"
        return 0
    fi

    if [ ! -d "${DEST_DIR}" ] && ! mkdir -p "${DEST_DIR}"; then
        echo_status "${term_fg_red}" "    Failed" "${DISPLAY_FILE_REF}"
        return 1
    fi

    # Create link and save status
    create_link "${SRC_FILE}" "${DEST_FILE}"
    local STATUS="${?}"

    if [ "${STATUS}" -eq 0 ]; then
        echo_status "${term_fg_green}" "   Created" "${DISPLAY_FILE_REF}"
    else
        echo_status "${term_fg_red}" "    Failed" "${DISPLAY_FILE_REF}"
    fi
    return "${STATUS}"
}

create_link() {
    local SRC_FILE="${1}"
    local DEST_FILE="${2}"
    local USE_SUDO="${3-0}"

    if [ "${MSYS}" -eq 1 ]; then
        [ -d "${SRC_FILE}" ] && OPT="/D " || OPT=""

        local WIN_SRC_FILE
        local WIN_DEST_FILE

        WIN_SRC_FILE="$(cygpath -w "${SRC_FILE}")"
        WIN_DEST_FILE="$(cygpath -w "${DEST_FILE}")"
        local CMD_C="mklink ${OPT}${WIN_DEST_FILE} ${WIN_SRC_FILE}"

        # Windows link attempt
        debug "cmd //C \"${CMD_C}\""

        # Double forward slash to prevent msys messing with params
        cmd //C "${CMD_C}" > /dev/null || return 1
    else
        local LINK_COMMAND=()
        if [ "${USE_SUDO}" -eq 1 ] && command -v sudo > /dev/null 2>&1; then
            LINK_COMMAND+=(sudo)
        fi
        LINK_COMMAND+=(ln -s "${SRC_FILE}" "${DEST_FILE}")
        # Unix link attempt
        "${LINK_COMMAND[@]}" > /dev/null 2>&1
    fi
}

backup_move() {
    local SRC="${1%/}"
    local FILE="${2##*/}"
    local FILE_STATUS="${3}"

    local DEST="${SRC/${HOME_DIR}/${BACKUP_DIR}}"
    local BACKUP_FILE

    BACKUP_FILE="$(filename "${FILE}")_${TIMESTAMP}$(extname "${FILE}")"

    if [ ! -d "${DEST}" ]; then
        if ! mkdir -p "${DEST}"; then
            error "Unable to create backup dir ${DEST}"
            return 1
        fi
    fi

    # Move to backup dir
    if ! mv "${SRC}/${FILE}" "${DEST}/${BACKUP_FILE}"; then
        echo_status "${term_fg_red}" "    Backup" "${FILE_STATUS}"
        return 1
    fi

    echo_status "${term_fg_green}" "    Backup" "${FILE_STATUS/${FILE}/${BACKUP_FILE}}"
}

# Is this a nested dir
#
# - should not sync dir
# - should sync contents
# - marked by containing an ignore file
#
is_nested_dir() {
    local DIR="${1%/}"
    if [ ! -d "${DIR}" ]; then
        return 1
    fi

    if [ ! -f "${DIR}/${DOTFILE_MARKER}" ]; then
        return 1
    fi

    return 0
}

# Create deep dir structure with ignore files for nesting
ensure_nested_dir() {
    local GROUP="${1}"
    local DIR="${2%/}"
    local IGNORE_FILE

    if [ ! -d "${DIR}" ] && ! mkdir -p "${DIR}"; then
        error "Unable to create nested dir: ${DIR}"
        return 1
    fi

    local CURRENT_DIR
    local END_DIR="${DOTFILES_DIR}/${GROUP}"

    CURRENT_DIR="${DIR}"
    while [ "${CURRENT_DIR}" != "${END_DIR}" ]; do
        IGNORE_FILE="${CURRENT_DIR}/${DOTFILE_MARKER}"
        if [ ! -f "${IGNORE_FILE}" ]; then
            if ! touch "${IGNORE_FILE}"; then
                error "Unable to create ${IGNORE_FILE}"
                return 1
            fi
            dotfile_git_add "${IGNORE_FILE}" || return 1
        fi

        CURRENT_DIR="$(dirname "${CURRENT_DIR}")"
    done

    return 0
}

cleanup_nested_dir() {
    local DOTFILE_GROUP_DIR="${1%/}"
    local EXPORT_DIR="${2%/}"
    local NESTED_DIR

    if [ -z "${DOTFILE_GROUP_DIR}" ]; then
        error "Missing dotfile group dir param"
        return 1
    fi

    if [ ! -d "${DOTFILE_GROUP_DIR}" ]; then
        error "Dotfile group dir must be a directory: ${DOTFILE_GROUP_DIR}"
        return 1
    fi

    if [ -z "${EXPORT_DIR}" ]; then
        error "Missing export dir param"
        return 1
    fi

    if [ ! -d "${EXPORT_DIR}" ]; then
        error "Export dir must be a directory: ${EXPORT_DIR}"
        return 1
    fi

    NESTED_DIR="${EXPORT_DIR}"
    while [ "${NESTED_DIR}" != "${DOTFILE_GROUP_DIR}" ]; do
        IGNORE_FILE="${NESTED_DIR}/${DOTFILE_MARKER}"

        # Not a nested dir
        if [ ! -f "${IGNORE_FILE}" ]; then
            break
        fi

        # Still has dotfiles
        while IFS= read -r -d $'\0'; do
            if [ "${REPLY}" != "${IGNORE_FILE}" ]; then
                break 2
            fi
        done < <(find "${NESTED_DIR}" -maxdepth 1 -mindepth 1 -print0)

        if ! rm "${IGNORE_FILE}"; then
            error "Failed to remove ${IGNORE_FILE}"
            return 1
        fi

        # Leave dir, delete it, reset NESTED_DIR
        if ! rmdir "${NESTED_DIR}"; then
            error "Failed to remove ${NESTED_DIR}"
            return 1
        fi
        dotfile_git_add "${NESTED_DIR}" || return 1
        NESTED_DIR="$(dirname "${NESTED_DIR}")"
    done

    return 0
}

ensure_config() {
    local PATH_CONFIG="${TRUE_HOME_DIR}/.config/dotfile"
    local FILE="${PATH_CONFIG}/config.ini"
    config_version=unknown

    if [ ! -d "${PATH}" ]; then
        if ! mkdir -p "${PATH_CONFIG}"; then
            error "Unable to create config dir: ${PATH_CONFIG}"
            exit 1
        fi
    fi

    if [ ! -f "${FILE}" ]; then
        create_config "${FILE}"
        if [ ! -f "${FILE}" ]; then
            error "Unable to create config file: ${FILE}"
            exit 1
        fi
    fi

    cfg_parser "${FILE}"
    if ! cfg_section_dotfile; then
        error "Failed to load config: ${FILE}"
        exit 1
    fi

    if [ "${config_version}" != "${MAJOR_VERSION}" ]; then
        error "Invalid config version!"
        echo "Config created for a different program version and may be incompatible"
        echo "  Program version: ${MAJOR_VERSION}"
        echo "   Config version: ${config_version}"
        echo "Update local config and retry"
        return 1
    fi

    return 0
}

create_config() {
    local FILE="${1}"

    if [ -z "${config_dir}" ]; then
        config_dir="~""/config"
    fi
    if [ -z "${config_repo}" ]; then
        config_repo=""
    fi

    cat << EOF >> "${FILE}"
[dotfile]
;;; compatability check
config_version=${MAJOR_VERSION}

;;; dir to clone config repo to
config_dir=${config_dir}

;;; config repo address
config_repo=${config_repo}

;;; comma delimited list of groups e.g. laptop,i3
custom_groups=
EOF
    sync
}

doc_title() {
    local LINE=""
    echo -n "${term_bold}${term_fg_blue}"
    while read -r LINE; do
        echo "${LINE}"
    done;
    echo -n "${term_reset}"
}

dir_status() {
    local TITLE="${1}"
    local DIR="${2}"
    local EXTRA="${3}"

    local COLOUR=""
    if [ -z "${DIR}" ]; then
        COLOUR="${term_fg_yellow}"
        DIR="path not set"
    elif [ -d "${DIR}" ] || [ -L "${DIR}" ]; then
        COLOUR="${term_fg_green}"
    else
        COLOUR="${term_fg_red}"
    fi
    echo_status "${COLOUR}" "${TITLE}" "${DIR}${EXTRA}"
}

implode() {
    local IFS="${1}"; shift;
    echo "${*}"
}

echo_status() {
    local COLOUR="${1}"
    local TITLE="${2}"
    local MESSAGE="${3}"
    echo "${TITLE} ${term_bold}${COLOUR}${MESSAGE}${term_reset}"
}

heading() {
    local MESSAGE="${1}"
    echo "${term_bold}${term_fg_green}:: ${term_fg_white}${MESSAGE}${term_reset}"
}

export_dotfile() {
    local EXPORT_FILE="${1}"

    local REPO_DIR
    local REPO_FILE
    local FILE_REF

    if [ ! -e "${EXPORT_FILE}" ]; then
        echo_status "${term_fg_red}" "   Missing" "${EXPORT_FILE}"
        return 1
    fi

    if [ "$(commonpath "${HOME_DIR}" "${EXPORT_FILE}")" != "${HOME_DIR}" ]; then
        error "File must be inside home dir: ${HOME_DIR}: ${EXPORT_FILE}"
        echo
        return 1
    fi

    if [ ! -L "${EXPORT_FILE}" ]; then
        echo_status "${term_fg_green}" "  Restored" "${EXPORT_FILE}"
        return 1
    fi

    REPO_FILE="$(readlink "${EXPORT_FILE}")"
    if [ -z "${REPO_FILE}" ]; then
        error "Missing linked file for ${EXPORT_FILE}"
        return 1
    fi
    if [ "$(commonpath "${DOTFILES_DIR}" "${REPO_FILE}")" != "${DOTFILES_DIR}" ]; then
        error "Link must point to file inside ${DOTFILES_DIR}: ${REPO_FILE}"
        echo
        return 1
    fi
    local FILE_REF="${REPO_FILE/${DOTFILES_DIR}\/*\//}"
    local DOTFILE_GROUP_DIR="${REPO_FILE/\/${FILE_REF}/}"
    REPO_DIR="${REPO_FILE%/*}"

    if [ "${PREVIEW}" -eq 1 ]; then
        echo_status "${term_fg_white}" "    Export" "${EXPORT_FILE}"
        return 0
    fi

    if ! rm "${EXPORT_FILE}"; then
        error "Failed to remove link ${EXPORT_FILE}"
        return 1
    fi
    if ! mv "${REPO_FILE}" "${EXPORT_FILE}"; then
        error "Failed to restore ${EXPORT_FILE}"
        return 1
    fi
    dotfile_git_add "${REPO_FILE}" || return 1

    if [ "${DOTFILE_GROUP_DIR}" != "${REPO_DIR}" ]; then
        cleanup_nested_dir "${DOTFILE_GROUP_DIR}" "${REPO_DIR}" || return 1
    fi

    echo_status "${term_fg_green}" "  Restored" "${EXPORT_FILE}"
}

import_dotfile() {
    local GROUP="${1}"
    local IMPORT_FILE
    IMPORT_FILE="$(abspath "${2}")"

    local FILE_REF="${IMPORT_FILE//${HOME_DIR}\//}"
    local DOTFILE_PATH="${DOTFILES_DIR}/${GROUP}/${FILE_REF}"
    local IMPORT_DIR="${IMPORT_FILE%/*}"

    if [ ! -e "${IMPORT_FILE}" ]; then
        echo_status "${term_fg_red}" "   Missing" "${FILE_REF}"
        return 1
    fi
    if [ -e "${DOTFILE_PATH}" ]; then
        echo_status "${term_fg_green}" "  Imported" "${FILE_REF}"
        return 1
    fi
    if [ -L "${IMPORT_FILE}" ]; then
        echo_status "${term_fg_red}" "    Linked" "${FILE_REF}"
        return 1
    fi

    if [ "${PREVIEW}" -eq 1 ]; then
        echo_status "${term_fg_white}" "    Import" "${FILE_REF}"
        return 0
    fi

    if [ "${HOME_DIR}" != "${IMPORT_DIR}" ]; then
        ensure_nested_dir "${GROUP}" "${DOTFILE_PATH%/*}" || return 1
    fi

    if ! mv "${IMPORT_FILE}" "${DOTFILE_PATH}"; then
        echo_status "${term_fg_red}" "    Failed" "${FILE_REF}"
        return 1
    fi

    if ! smart_link "${GROUP}" "${FILE_REF}" ; then
        return 1
    fi
    echo_status "${term_fg_green}" "  Imported" "${FILE_REF}"

    dotfile_git_add "${DOTFILE_PATH}"
}

display_ensure_filesystem() {
    if [ "${PREVIEW}" -eq 1 ]; then
        info "Preview"
        echo
    fi

    local HEADING
    [ -n "${DOTFILES_REPO}" ] && HEADING="${DOTFILES_REPO}" || HEADING="${DOTFILES_DIR}"
    heading "Dotfiles ${term_fg_green}${HEADING}${term_reset}"

    display_ensure_dir "${DOTFILES_DIR}" "config" || return 1
    display_ensure_dir "${BACKUP_DIR}" "backup" || return 1
    ensure_dotfiles_dir || return 1

    local SUCCESS=0
    local DOTFILE_GROUP
    for DOTFILE_GROUP in "${DOTFILE_GROUP_LIST[@]}"; do
        display_ensure_dir "${DOTFILES_DIR}/${DOTFILE_GROUP}" "${DOTFILE_GROUP} group" || SUCCESS=1
    done
    echo

    return "${SUCCESS}"
}

ensure_dotfiles_dir() {
    [ -d "${DOTFILES_DIR}" ] && return 0

    if [ -z "${DOTFILES_REPO}" ]; then
        error "Missing dotfiles repo config"
        return 1
    fi

    if ! clone_repo "${DOTFILES_REPO}" "${DOTFILES_DIR}"; then
        error "Failed to clone ${DOTFILES_REPO}"
        echo
        return 1
    fi

    [ -d "${DOTFILES_DIR}" ]
}

sync_config_to_home() {
    local GROUP
    local SRC_DIR
    local EXCLUDE_NAMES=()
    local EXCLUDE_PATHS=()
    local FILE
    local FILE_REF

    heading "Sync ${HOME_DIR}"

    if [ "${#DOTFILE_GROUP_LIST[@]}" = 0 ]; then
        echo "No repo groups available"
        return 1
    fi

    local SYNC_EXCLUDE
    for SYNC_EXCLUDE in "${SYNC_EXCLUDE_LIST[@]}"; do
        EXCLUDE_NAMES+=(-not -name "${SYNC_EXCLUDE}")
    done

    local STATUS=0
    # Spin through groups syncing files
    # Skip files handled by a previous group
    for GROUP in "${DOTFILE_GROUP_LIST[@]}"; do
        SRC_DIR="${DOTFILES_DIR}/${GROUP}"
        debug "Checking ${SRC_DIR}"

        while read -r -d $'\0' FILE; do
            # Skip dir if it contains a `${DOTFILE_MARKER}`
            if [ -d "${FILE}" ] && [ -f "${FILE}/${DOTFILE_MARKER}" ]; then
                debug "Skip nested dir: ${FILE}"
                continue
            fi

            # Skip file unless it's next to a `${DOTFILE_MARKER}`
            if [ -e "${FILE}" ] && [ ! -f "${FILE%/*}/${DOTFILE_MARKER}" ]; then
                debug "Skip non dotfile: ${FILE}"
                continue
            fi

            FILE_REF="${FILE/${DOTFILES_DIR}\/${GROUP}\//}"

            # Make sure we don't match this file again in another group
            EXCLUDE_PATHS+=(-not -path "${DOTFILES_DIR}/*/${FILE_REF}")

            smart_link "${GROUP}" "${FILE_REF}" || STATUS=1
        done < <(find "${SRC_DIR}" -mindepth 1 "${EXCLUDE_NAMES[@]}" "${EXCLUDE_PATHS[@]}" -print0)
    done

    if [ "${#EXCLUDE_PATHS[@]}" -eq 0 ]; then
        info "No files in config repo, get started with \"dotfile import\""
    fi
    echo

    return "${STATUS}"
}

load_global_variables || exit 1

dispatch dotfile "$@"
